services:
  mongo:
    image: mongo:7
    container_name: booklend-dev-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./back-end/.env.prod
      - ./back-end/.env
      - ./.env.local.example
      - ./.env.local
    depends_on:
      - mongo

volumes:
  mongo_data:
