services:
  mongo:
    image: mongo:7
    container_name: booklend-db
    ports:
      - "27017:27017"
    volumes: 
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  server:
    image: node:24
    container_name: booklend-api
    depends_on:
      - mongo
    env_file:
      - .env
      - .env.prod
      - .env.local
    ports:
      - "3000:3000"
    command: sh -c "npm run build; npm run start"
    working_dir: /server
    volumes:
      - .:/server
      - /server/node_modules

volumes:
  mongo_data:
